export const ROUTES = {
  AUTH: {
    LOGIN: '/auth/login',
    VERIFY: '/auth/verify',
    PROFILE: '/auth/profile',
  },
  HOME: '/home',
  CHAT: {
    LIST: '/home',
    SEARCH: '/home/search',
    SEARCH_MESSAGES: '/home/search/messages',
    ADD: '/home/add',
    CREATE_GROUP: '/home/create-group',
    ARCHIVED: '/home/archived',
    PINNED: '/home/pinned',
    CONVERSATION: '/home/c/:conversationId',
    DETAILS: '/home/c/:conversationId/details',
    GROUP: '/home/g/:groupId',
    GROUP_DETAILS: '/home/g/:groupId/details',
    MEDIA: '/home/c/:conversationId/media',
    CONVERSATION_SEARCH: '/home/c/:conversationId/search',
  },
  GROUP: {
    DETAIL: '/home/g/:groupId/details',
    MEMBERS: '/home/g/:groupId/members',
    ROLES: '/home/g/:groupId/roles',
    INVITE: '/home/g/:groupId/invite',
    SETTINGS: '/home/g/:groupId/settings',
  },
  EXPLORE: '/explore',
  UPDATES: '/updates',
  CHANNEL: {
    ROOT: '/channels',
    DISCOVER: '/channels/discover',
    CREATE: '/channels/create',
    FEED: '/channels/:channelId',
    DETAILS: '/channels/:channelId/details',
    INVITE: '/channels/:channelId/invite',
    ANALYTICS: '/channels/:channelId/analytics',
    SETTINGS: '/channels/:channelId/settings',
    ADMINS: '/channels/:channelId/admins',
    POSTS: '/channels/:channelId/posts',
  },
  COMMUNITY: {
    ROOT: '/communities',
    DISCOVER: '/communities/discover',
    JOIN: '/communities/join/:communityId',
    DETAILS: '/communities/:communityId',
    OVERVIEW: '/communities/:communityId/overview',
    MEMBERS: '/communities/:communityId/members',
    GROUPS: '/communities/:communityId/groups',
    CHANNELS: '/communities/:communityId/channels',
    ABOUT: '/communities/:communityId/about',
    MANAGE: '/communities/:communityId/manage',
    CREATE: '/communities/create',
  },
  STORY_VIEWER: '/stories/viewer',
  STORY_CREATE: '/stories/create',
  CONTACTS: {
    ROOT: '/contacts',
    ADD: '/contacts/add',
  },
  SEARCH: '/search',
  NOTIFICATIONS: '/notifications',
  PROFILE: {
    SELF: '/profile',
    USER: '/profile/:username',
    EDIT: '/profile/edit',
  },
  SETTINGS: {
    ROOT: '/settings',
    PROFILE: '/settings/profile',
    ACCOUNT: '/settings/account',
    PRIVACY: '/settings/privacy',
    SECURITY: '/settings/security',
    NOTIFICATIONS: '/settings/notifications',
    CHATS: '/settings/chats',
    STORAGE: '/settings/storage',
    APPEARANCE: '/settings/appearance',
    LANGUAGE: '/settings/language',
    DEVICES: '/settings/devices',
    HELP: '/settings/help',
    ABOUT: '/settings/about',
  },
  ORGANIZATIONS: {
    LIST: '/organizations',
    CREATE: '/organizations/create',
    DETAIL: '/organizations/:orgId',
    SETTINGS: '/organizations/:orgId/settings',
  },
  MODERATION: {
    DASHBOARD: '/admin',
    REPORTS: '/admin/reports',
    BANS: '/admin/bans',
  },
  ADMIN: {
    LOGIN: '/admin/login',
    ROOT: '/admin',
    USERS: '/admin/users',
    ADMINISTRATORS: '/admin/administrators',
    INSTITUTIONS: '/admin/institutions',
    REPORTS: '/admin/reports',
    CONTENT: '/admin/content',
  },
} as const
