import { useNavigate } from 'react-router'
import { useAuth } from '@/app/providers/AuthProvider'
import { Button } from '@/core/components/ui/Button'
import { PageContainer } from '@/core/components/layout/PageContainer'
import { ROUTES } from '@/core/utils/routes'

const sections = [
  { label: 'Account', items: [{ title: 'Profile settings', description: 'Display name, avatar, bio, and status', path: ROUTES.SETTINGS.PROFILE, icon: '◎' }, { title: 'Account settings', description: 'Phone, email, and account controls', path: ROUTES.SETTINGS.ACCOUNT, icon: '@' }] },
  { label: 'Privacy & security', items: [{ title: 'Privacy', description: 'Last seen, read receipts, and blocked users', path: ROUTES.SETTINGS.PRIVACY, icon: '◈' }, { title: 'Security', description: 'App lock, PIN, and active sessions', path: ROUTES.SETTINGS.SECURITY, icon: '⌑' }, { title: 'Devices', description: 'Active sessions and linked devices', path: ROUTES.SETTINGS.DEVICES, icon: '▣' }] },
  { label: 'Preferences', items: [{ title: 'Notifications', description: 'Alerts, sounds, and message previews', path: ROUTES.SETTINGS.NOTIFICATIONS, icon: '◌' }, { title: 'Chat settings', description: 'Composer, downloads, wallpaper, and backups', path: ROUTES.SETTINGS.CHATS, icon: '▱' }, { title: 'Storage & data', description: 'Cached media, downloads, and network usage', path: ROUTES.SETTINGS.STORAGE, icon: '▤' }, { title: 'Appearance', description: 'Theme and conversation presentation', path: ROUTES.SETTINGS.APPEARANCE, icon: '◐' }, { title: 'Language', description: 'Choose the language used across Wisal', path: ROUTES.SETTINGS.LANGUAGE, icon: '文' }] },
  { label: 'Support', items: [{ title: 'Help & support', description: 'FAQ, contact support, and report a problem', path: ROUTES.SETTINGS.HELP, icon: '?' }, { title: 'About', description: 'Version, licenses, legal, and credits', path: ROUTES.SETTINGS.ABOUT, icon: 'i' }] },
]

export default function SettingsPage() {
  const navigate = useNavigate()
  const { logout } = useAuth()
  return <div className="flex h-full flex-col bg-black text-[#e7e9ea]"><PageContainer className="mx-auto w-full max-w-3xl px-4 pt-5 pb-10 sm:px-6"><header className="border-b border-[#2f3336] pb-5"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#1d9bf0]">Preferences</p><h1 className="mt-2 text-2xl font-bold sm:text-3xl">Settings</h1><p className="mt-2 max-w-lg text-sm leading-relaxed text-[#71767b]">Manage your account, privacy, and conversation experience.</p></header><div className="mt-6 space-y-6">{sections.map((section) => <section key={section.label}><h2 className="mb-2 px-1 text-xs font-bold uppercase tracking-wider text-[#71767b]">{section.label}</h2><div className="overflow-hidden rounded-2xl border border-[#2f3336] bg-[#16181c]">{section.items.map((item) => <button type="button" key={item.path} onClick={() => navigate(item.path)} className="group flex w-full items-center gap-3 border-b border-[#2f3336] p-4 text-left transition-colors last:border-b-0 hover:bg-white/[0.03] cursor-pointer"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-[#1d9bf0]/10 text-sm font-bold text-[#1d9bf0]">{item.icon}</span><span className="min-w-0 flex-1"><span className="block truncate text-[15px] font-bold">{item.title}</span><span className="mt-1 block truncate text-xs text-[#71767b]">{item.description}</span></span><span className="text-lg text-[#71767b] transition-colors group-hover:text-[#1d9bf0]">→</span></button>)}</div></section>)}</div><Button variant="danger" className="mt-8 w-full" onClick={() => { logout(); navigate(ROUTES.AUTH.LOGIN) }}>Log out</Button><p className="mt-5 text-center text-[10px] text-[#71767b]">Wisal v0.1.0</p></PageContainer></div>
}
