import { useState } from 'react'
import { PageContainer } from '@/core/components/layout/PageContainer'
import { BackButton } from '@/core/components/ui/BackButton'
import { Button } from '@/core/components/ui/Button'
import { ROUTES } from '@/core/utils/routes'

const initialAdmins = [{ id: 'owner', name: 'System owner', role: 'Owner', active: true }, { id: 'moderator', name: 'Safety moderator', role: 'Moderator', active: true }, { id: 'reviewer', name: 'Content reviewer', role: 'Reviewer', active: true }]

export default function AdministratorsPage() {
  const [admins, setAdmins] = useState(initialAdmins)
  return <div className="flex h-full flex-col bg-black"><PageContainer className="w-full max-w-3xl px-3 pt-3 sm:px-5"><BackButton to={ROUTES.ADMIN.ROOT} label="Overview" /><div className="mt-3 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-[#71767b]">Access control</p><h1 className="mt-1 text-2xl font-bold text-[#e7e9ea]">Administrators</h1></div><Button size="sm" onClick={() => setAdmins((current) => [...current, { id: `admin-${current.length}`, name: 'New supervisor', role: 'Supervisor', active: true }])}>Add supervisor</Button></div><div className="mt-5 overflow-hidden rounded-2xl border border-[#2f3336] bg-[#16181c]">{admins.map((admin) => <div key={admin.id} className="flex items-center gap-3 border-b border-[#2f3336] px-4 py-4 last:border-b-0"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-[#1d9bf0]/10 text-sm font-bold text-[#1d9bf0]">{admin.name.slice(0, 1)}</div><div className="min-w-0 flex-1"><p className="font-bold text-[#e7e9ea]">{admin.name}</p><p className="text-xs text-[#71767b]">{admin.role} · {admin.active ? 'Active' : 'Suspended'}</p></div><div className="flex items-center gap-2"><select aria-label={`Role for ${admin.name}`} value={admin.role} disabled={admin.id === 'owner'} onChange={(event) => setAdmins((current) => current.map((item) => item.id === admin.id ? { ...item, role: event.target.value } : item))} className="h-9 rounded-full border border-[#2f3336] bg-[#202327] px-3 text-xs text-[#e7e9ea] outline-none focus:border-[#1d9bf0] disabled:opacity-60"><option>Owner</option><option>Manager</option><option>Administrator</option><option>Moderator</option><option>Reviewer</option></select><button type="button" disabled={admin.id === 'owner'} onClick={() => setAdmins((current) => current.map((item) => item.id === admin.id ? { ...item, active: !item.active } : item))} className="rounded-full px-3 py-1.5 text-xs font-bold text-[#1d9bf0] hover:bg-[#1d9bf0]/10 disabled:cursor-not-allowed disabled:opacity-40 cursor-pointer">{admin.active ? 'Suspend' : 'Restore'}</button></div></div>)}</div></PageContainer></div>
}
