export const communities = [
  {
    id: 'builders-hub',
    name: 'مركز البناة',
    description: 'مساحة مركزة لبناة المنتجات والمصممين والمهندسين الذين يطورون أدوات تعاونية.',
    category: 'المنتج',
    members: '24.8k',
    groups: 12,
    channels: 6,
    joined: true,
    owner: true,
    verified: true,
    unreadCount: 3,
    lastMessage: 'سارة: سنطلق الواجهة الجديدة غدًا! 🚀',
    lastMessageTime: '11:42 ص',
    groupList: [
      { id: 'g-launch-planning', name: 'تخطيط الإطلاق', members: '1.2k', lastMessage: 'سارة: سنطلق الواجهة الجديدة غدًا! 🚀', isMuted: false },
      { id: 'g-product-feedback', name: 'ملاحظات المنتج', members: '640', lastMessage: 'خالد: تم إصلاح الثغرة في الإعدادات.', isMuted: true },
      { id: 'g-design-crit', name: 'نقد التصميم', members: '310', lastMessage: 'نور: أرسلت ذلك التعديل في فيجما.', isMuted: false },
    ],
    channelIds: ['product-updates', 'design-systems'],
  },
  {
    id: 'design-guild',
    name: 'نقابة التصميم',
    description: 'نقد وملاحظات بحثية ومراجعات إمكانية الوصول وتفكير أنظمة.',
    category: 'التصميم',
    members: '8.6k',
    groups: 7,
    channels: 4,
    joined: true,
    owner: false,
    verified: false,
    unreadCount: 0,
    lastMessage: 'أليكس: إرشادات نظام العلامة التجارية أصبحت الآن في فيجما.',
    lastMessageTime: 'أمس',
    groupList: [
      { id: 'g-brand-systems', name: 'أنظمة العلامة التجارية', members: '890', lastMessage: 'أليكس: إرشادات نظام العلامة الآن في فيجما.', isMuted: false },
      { id: 'g-accessibility', name: 'إمكانية الوصول', members: '420', lastMessage: 'مريم: من أبدأ مراجعة الوضوح؟', isMuted: false },
    ],
    channelIds: ['design-systems'],
  },
  {
    id: 'startup-ops',
    name: 'عمليات الشركات الناشئة',
    description: 'أدلة تشغيلية للفرق النامية وقادة الدعم والمؤسسين.',
    category: 'العمليات',
    members: '14.1k',
    groups: 9,
    channels: 5,
    joined: false,
    owner: false,
    verified: true,
    unreadCount: 0,
    lastMessage: 'فريق العمليات: تم رفع دليل بدء التشغيل الجديد.',
    lastMessageTime: '26 يوليو',
    groupList: [
      { id: 'g-support-leads', name: 'قادة الدعم', members: '1.1k', lastMessage: 'فريق العمليات: دليل بدء التشغيل أصبح متاحًا.', isMuted: false },
      { id: 'g-fundraising', name: 'التواصل مع المستثمرين', members: '280', lastMessage: 'رنا: اجتماع المتابعة يوم الخميس.', isMuted: true },
    ],
    channelIds: ['engineering-briefs'],
  },
]

export const communityActivity = [
  'نشرت نقابة التصميم إرشادات جديدة لغرفة النقد.',
  'فتح مركز البناة مجموعة فرعية لتخطيط الإطلاق.',
  'شاركت عمليات الشركات الناشئة قالب تصعيد الدعم.',
]
