export const communities = [
  {
    id: 'builders-hub',
    name: 'Builders Hub',
    description: 'A focused space for product builders, designers, and engineers shipping collaborative tools.',
    category: 'Product',
    members: '24.8k',
    groups: 12,
    channels: 6,
    joined: true,
    verified: true,
    unreadCount: 3,
    lastMessage: 'Sarah: We are launching the new UI tomorrow! 🚀',
    lastMessageTime: '11:42 AM',
  },
  {
    id: 'design-guild',
    name: 'Design Guild',
    description: 'Critiques, research notes, accessibility reviews, and systems thinking.',
    category: 'Design',
    members: '8.6k',
    groups: 7,
    channels: 4,
    joined: true,
    verified: false,
    unreadCount: 0,
    lastMessage: 'Alex: The brand system guidelines are now in Figma.',
    lastMessageTime: 'Yesterday',
  },
  {
    id: 'startup-ops',
    name: 'Startup Ops',
    description: 'Operational playbooks for growing teams, support leaders, and founders.',
    category: 'Operations',
    members: '14.1k',
    groups: 9,
    channels: 5,
    joined: false,
    verified: true,
    unreadCount: 0,
    lastMessage: 'Ops Team: New startup playbook has been uploaded.',
    lastMessageTime: 'Jul 26',
  },
]

export const communityActivity = [
  'Design Guild published new critique room guidelines.',
  'Builders Hub opened a subgroup for launch planning.',
  'Startup Ops shared a support escalation template.',
]
