export const communities = [
  {
    id: 'builders-hub',
    name: 'مركز البناة',
    description: 'مساحة مركزة لبناة المنتجات والمصممين والمهندسين الذين يطورون أدوات تعاونية.',
    category: 'المنتج',
    members: '24.8k',
    groups: 12,
    joined: true,
    owner: true,
    verified: true,
    unreadCount: 3,
    lastMessage: 'سارة: سنطلق الواجهة الجديدة غدًا! 🚀',
    lastMessageTime: '11:42 ص',
    groupList: [
      { id: 'g-launch-planning', name: 'تخطيط الإطلاق', members: '1.2k', lastMessage: 'سارة: سنطلق الواجهة الجديدة غدًا! 🚀', isMuted: false },
      { id: 'g-product-feedback', name: 'ملاحظات المنتج', members: '640', lastMessage: 'خالد: تم إصلاح الثغرة في الإعدادات.', isMuted: true },
      { id: 'g-design-crit', name: 'نقد التصميم', members: '310', lastMessage: 'نور: أرسلت ذلك التعديل في فيجما.', isMuted: false },
    ],
    channels: [
      {
        id: 'ann-builders',
        name: 'الإعلانات',
        description: 'القناة الرسمية لمركز البناة. تصدر الإدارة هنا الإعلانات والتحديثات الرئيسية فقط.',
        category: 'إعلانات',
        subscribers: '18.4k',
        posts: 12,
        joined: true,
        admin: true,
        verified: true,
        isAnnouncement: true,
        hasNewUpdate: true,
        lastPost: 'سارة: سنطلق الواجهة الجديدة غدًا! 🚀',
        lastPostTime: '3 س',
      },
      {
        id: 'product-updates',
        name: 'Product Updates',
        description: 'Release notes, launch previews, and adoption notes for the product team.',
        category: 'المنتج',
        subscribers: '18.4k',
        posts: 42,
        joined: true,
        admin: true,
        verified: true,
        hasNewUpdate: true,
        lastPost: 'Real-time collaboration is now live for workspace beta users.',
        lastPostTime: '2 س مضت',
      },
      {
        id: 'design-systems',
        name: 'Design Systems Weekly',
        description: 'Reusable UI patterns, component decisions, and visual QA notes.',
        category: 'التصميم',
        subscribers: '9.2k',
        posts: 31,
        joined: true,
        admin: false,
        verified: true,
        hasNewUpdate: true,
        lastPost: 'The mobile composer now supports file previews and image drafts.',
        lastPostTime: '5 س مضت',
      },
    ],
  },
  {
    id: 'design-guild',
    name: 'نقابة التصميم',
    description: 'نقد وملاحظات بحثية ومراجعات إمكانية الوصول وتفكير أنظمة.',
    category: 'التصميم',
    members: '8.6k',
    groups: 7,
    joined: true,
    owner: false,
    verified: false,
    unreadCount: 0,
    lastMessage: 'أليكس: إرشادات نظام العلامة التجارية أصبحت الآن في فيجما.',
    lastMessageTime: 'أمس',
    groupList: [
      { id: 'g-brand-systems', name: 'أنظمة العلامة التجارية', members: '890', lastMessage: 'أليكس: إرشادات نظام العلامة الآن في فيجما.', isMuted: false },
      { id: 'g-accessibility', name: 'إمكانية الوصول', members: '420', lastMessage: 'مريم: من أبدأ مراجعة الوضوح؟', isMuted: false },
    ],
    channels: [
      {
        id: 'ann-design-guild',
        name: 'الإعلانات',
        description: 'القناة الرسمية لنقابة التصميم. تصدر الإدارة هنا الإعلانات والتحديثات الرئيسية فقط.',
        category: 'إعلانات',
        subscribers: '8.6k',
        posts: 8,
        joined: true,
        admin: false,
        verified: false,
        isAnnouncement: true,
        hasNewUpdate: false,
        lastPost: 'تم تحديث إرشادات غرفة النقد وتوفرها الآن في فيجما.',
        lastPostTime: 'أمس',
      },
      {
        id: 'design-systems',
        name: 'Design Systems Weekly',
        description: 'Reusable UI patterns, component decisions, and visual QA notes.',
        category: 'التصميم',
        subscribers: '9.2k',
        posts: 31,
        joined: true,
        admin: false,
        verified: true,
        hasNewUpdate: true,
        lastPost: 'The mobile composer now supports file previews and image drafts.',
        lastPostTime: '5 س مضت',
      },
    ],
  },
  {
    id: 'startup-ops',
    name: 'عمليات الشركات الناشئة',
    description: 'أدلة تشغيلية للفرق النامية وقادة الدعم والمؤسسين.',
    category: 'العمليات',
    members: '14.1k',
    groups: 9,
    joined: false,
    owner: false,
    verified: true,
    unreadCount: 0,
    lastMessage: 'فريق العمليات: تم رفع دليل بدء التشغيل الجديد.',
    lastMessageTime: '26 يوليو',
    groupList: [
      { id: 'g-support-leads', name: 'قادة الدعم', members: '1.1k', lastMessage: 'فريق العمليات: دليل بدء التشغيل أصبح متاحًا.', isMuted: false },
      { id: 'g-fundraising', name: 'التواصل مع المستثمرين', members: '280', lastMessage: 'رنا: اجتماع المتابعة يوم الخميس.', isMuted: true },
    ],
    channels: [
      {
        id: 'ann-startup-ops',
        name: 'الإعلانات',
        description: 'القناة الرسمية لعمليات الشركات الناشئة. تصدر الإدارة هنا الإعلانات والتحديثات الرئيسية فقط.',
        category: 'إعلانات',
        subscribers: '14.1k',
        posts: 21,
        joined: false,
        admin: false,
        verified: true,
        isAnnouncement: true,
        hasNewUpdate: true,
        lastPost: 'تم رفع دليل بدء التشغيل الجديد لفريق العمليات.',
        lastPostTime: '26 يوليو',
      },
      {
        id: 'engineering-briefs',
        name: 'Engineering Briefs',
        description: 'Architecture updates, incident notes, and build health summaries.',
        category: 'الهندسة',
        subscribers: '12.7k',
        posts: 55,
        joined: false,
        admin: false,
        verified: false,
        hasNewUpdate: false,
        lastPost: 'Admin analytics have been refreshed with subscriber growth.',
        lastPostTime: '2 ي مضت',
      },
    ],
  },
]

export const communityActivity = [
  'نشرت نقابة التصميم إرشادات جديدة لغرفة النقد.',
  'فتح مركز البناة مجموعة فرعية لتخطيط الإطلاق.',
  'شاركت عمليات الشركات الناشئة قالب تصعيد الدعم.',
]
