export const channels = [
  {
    id: 'product-updates',
    name: 'Product Updates',
    description: 'Release notes, launch previews, and adoption notes for the product team.',
    category: 'Product',
    subscribers: '18.4k',
    posts: 42,
    joined: true,
    admin: true,
    verified: true,
    hasNewUpdate: true,
    lastPost: 'Real-time collaboration is now live for workspace beta users.',
    lastPostTime: '2h ago',
  },
  {
    id: 'design-systems',
    name: 'Design Systems Weekly',
    description: 'Reusable UI patterns, component decisions, and visual QA notes.',
    category: 'Design',
    subscribers: '9.2k',
    posts: 31,
    joined: true,
    admin: false,
    verified: true,
    hasNewUpdate: true,
    lastPost: 'The mobile composer now supports file previews and image drafts.',
    lastPostTime: '5h ago',
  },
  {
    id: 'engineering-briefs',
    name: 'Engineering Briefs',
    description: 'Architecture updates, incident notes, and build health summaries.',
    category: 'Engineering',
    subscribers: '12.7k',
    posts: 55,
    joined: false,
    admin: false,
    verified: false,
    hasNewUpdate: false,
    lastPost: 'Admin analytics have been refreshed with subscriber growth.',
    lastPostTime: '2d ago',
  },
]

export const channelPosts = [
  'Real-time collaboration is now live for workspace beta users.',
  'The mobile composer now supports file previews and image drafts.',
  'Admin analytics have been refreshed with subscriber growth and post reach.',
]
